Evidence8MVCAndjQueryAjax/Models/tblUser.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidence8MVCAndjQueryAjax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ImageName { get; set; }
        public string ImageUrl { get; set; }
    }
}

Evidence8MVCAndjQueryAjax/Controllers/tblUserController.cs
using Evidence8MVCAndjQueryAjax.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Evidence8MVCAndjQueryAjax.Controllers
{
    public class tblUserController : Controller
    {
        ContextDBEntities1 db = new ContextDBEntities1();
        public ActionResult Index(string SearchString, string CurrentFilter, string SortOrder, int? page)
        {
            List<UserViewModel> userList = db.tblUsers.Select(u => new UserViewModel
            {
                Id = u.Id,
                UserName = u.UserName,
                Email = u.Email,
                DOB = u.DOB,
                ImageName = u.ImageName,
                ImageUrl = u.ImageUrl
            }).ToList();
            ViewBag.SortNameParam = string.IsNullOrEmpty(SortOrder) ? "name_desc" : "";
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = CurrentFilter;
            }
            ViewBag.CurrentFilter = SearchString;        

            var list = userList;
            if(!string.IsNullOrEmpty(SearchString))
            {
                list = list.Where(u => u.UserName.ToUpper().
                Contains(SearchString.ToUpper())).ToList();
            }
            switch (SortOrder)
            {
                case "name_desc":
                    list = list.OrderByDescending(u => u.UserName).ToList();
                    break;
                default:
                    list = list.OrderBy(u => u.UserName).ToList();
                    break;
            }
            int PageSize = 3;
            int PageNumber = (page ?? 1);
            
            return View(list.ToPagedList(PageNumber,PageSize));
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(UserViewModel vobj)
        {
            var result = false;
            try
            {
                tblUser obj;
                if(vobj.Id==0)
                {
                    obj = new tblUser();
                    obj.UserName = vobj.UserName;
                    obj.Email = vobj.Email;
                    obj.DOB = vobj.DOB;
                    string fileName = Path.GetFileNameWithoutExtension(vobj.ImageFile.FileName);
                    string extension = Path.GetExtension(vobj.ImageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    vobj.ImageUrl = "~/Images/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Images/" + fileName));
                    vobj.ImageFile.SaveAs(fileName);
                    obj.ImageName = vobj.ImageName;
                    obj.ImageUrl = vobj.ImageUrl;
                    db.tblUsers.Add(obj);
                    db.SaveChanges();
                    result = true;
                }
                else
                {
                    obj = db.tblUsers.SingleOrDefault(u => u.Id == vobj.Id);
                    obj.UserName = vobj.UserName;
                    obj.Email = vobj.Email;
                    obj.DOB = vobj.DOB;
                    string fileName = Path.GetFileNameWithoutExtension(vobj.ImageFile.FileName);
                    string extension = Path.GetExtension(vobj.ImageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    vobj.ImageUrl = "~/Images/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Images/" + fileName));
                    vobj.ImageFile.SaveAs(fileName);
                    obj.ImageName = vobj.ImageName;
                    obj.ImageUrl = vobj.ImageUrl;                    
                    db.SaveChanges();
                    result = true;

                }
                if(result)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
           
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
           tblUser  obj = db.tblUsers.SingleOrDefault(u => u.Id == id);
            UserViewModel vobj = new UserViewModel();
            vobj.UserName = obj.UserName;
            vobj.Email = obj.Email;
            vobj.DOB = obj.DOB;
            vobj.ImageName = obj.ImageName;
            vobj.ImageUrl = obj.ImageUrl;
            vobj.Id = obj.Id;
            return View(vobj);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            tblUser obj = db.tblUsers.SingleOrDefault(u => u.Id == id);
            UserViewModel vobj = new UserViewModel();
            vobj.UserName = obj.UserName;
            vobj.Email = obj.Email;
            vobj.DOB = obj.DOB;
            vobj.ImageName = obj.ImageName;
            vobj.ImageUrl = obj.ImageUrl;
            vobj.Id = obj.Id;
            return View(vobj);
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            tblUser obj = db.tblUsers.SingleOrDefault(u => u.Id == id);
            if(obj!=null)
            {
                db.tblUsers.Remove(obj);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(obj);
            }
            
        }
        public PartialViewResult Details(int id)
        {
            tblUser obj = db.tblUsers.SingleOrDefault(u => u.Id == id);
            UserViewModel vobj = new UserViewModel();
            vobj.UserName = obj.UserName;
            vobj.Email = obj.Email;
            vobj.DOB = obj.DOB;
            vobj.ImageName = obj.ImageName;
            vobj.ImageUrl = obj.ImageUrl;
            vobj.Id = obj.Id;
            ViewBag.Details = "Show";
            return PartialView("_UserDetails", vobj);
        }
     }
}

Evidence8MVCAndjQueryAjax/Views/tblUser/Create.cshtml
@model Evidence8MVCAndjQueryAjax.Models.UserViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<h2>Create</h2>


@using (Html.BeginForm("Create", "tblUser", FormMethod.Post, new { @enctype="multipart/form-data" , @id="SubmitForm"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" name="ImageFile" required/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" onclick="SaveUser()" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(document).ready(function () {
        $("#DOB").datepicker(
            {
                appendText: 'mm/dd/yyyy',
                showOn: 'both',
                buttonText: 'Click Here',
                dateFormat: 'mm/dd/yy',
                changeMonth: true,
                changeYear: true,
                minDate: new Date(1970, 1, 1),
                maxDate: new Date(2025, 1, 1)
            }
        );
    });
    function SaveUser() {
        var data = $("#SubmitForm").serialize();
        var file = $("#ImageFile").get(0).files;
        data.append("ImageFile", file[0]);
        $.ajax({
            type: "POST",
            url: "/tblUser/Create/",
            data: data,
            success: function () {
                alert("Saved successfully");
                window.location.href("/tblUser/Index/")
            },
            error: function () {
                alert("Error occured");
            }
        });
    }

</script>

Evidence8MVCAndjQueryAjax/Views/tblUser/Delete.cshtml
@model Evidence8MVCAndjQueryAjax.Models.UserViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            <img src="@Url.Content(Model.ImageUrl)" alt=@Model.ImageName width="50" height="50" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Evidence8MVCAndjQueryAjax/Views/tblUser/Edit.cshtml
@model Evidence8MVCAndjQueryAjax.Models.UserViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<h2>Edit</h2>

@using (Html.BeginForm("Create", "tblUser", FormMethod.Post , new { @enctype = "multipart/form-data", @id = "SubmitForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(Model.ImageUrl)" alt=@Model.ImageName width="50" height="50" />
                <input type="file" name="ImageFile" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(document).ready(function () {
        $("#DOB").datepicker(
            {
                appendText: 'mm/dd/yyyy',
                showOn: 'both',
                buttonText: 'Click Here',
                dateFormat: 'mm/dd/yy',
                changeMonth: true,
                changeYear: true,
                minDate: new Date(1970, 1, 1),
                maxDate: new Date(2025, 1, 1)
            }
        );
    });
   

</script>

Evidence8MVCAndjQueryAjax/Views/tblUser/Index.cshtml
@model PagedList.PagedList<Evidence8MVCAndjQueryAjax.Models.UserViewModel>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}
<link href="~/Content/PagedList.css" rel="stylesheet" />
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary btn-large" })
</p>
@using (Html.BeginForm("Index", "tblUser", FormMethod.Get))
{<p>
        Find By Name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" class="btn btn-primary" />
    </p>

}
<table class="table">
    <tr>
        <th>
            User Name
        </th>
        <th>
            Email Address
        </th>
        <th>
            Date of Birth
        </th>
        <th>
            Image Name
        </th>
        <th>
            Image
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.DOB))
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageName)
            </td>
            <td>
                <img src="@Url.Content(item.ImageUrl)" alt=@item.ImageName width="40" height="40" />
            </td>
            <td>
                <a href="#" name="details" onclick="DetailsRecord('+@item.Id+')">Details</a>|
                @*@Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)Of @Model.PageCount

@Html.PagedListPager(Model,page=>Url.Action("Index",
    new { page,SortOrder=ViewBag.CurrentSort, CurrentFilter= ViewBag.CurrentFilter }))

<div id="partialDiv">
    @if (ViewBag.Details == "Show")
    {
        @Html.Partial("_UserDetails", Model)
        ViewBag.Details = "";
    }

</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    function DetailsRecord(id) {
        $.ajax({
            url: "/tblUser/Details?Id=" + id,
            type: 'GET',
            data: "",
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                $("#partialDiv").show();
                $("#partialDiv").html(data);
            },
            error: function () {
                alert("Error occured");
            }
        })
    }
    
</script>